[YottaDB/DB/YDB#1164] Handle GVUNDEF/LVUNDEF case in _yottadb.c now that $zstatus is not maintained
Background
----------
Below is pasted from https://gitlab.com/YottaDB/Lang/YDBPython/-/merge_requests/81#note_2692813056

* Below is what the [YDBPython get() documentation]
  (https://docs.yottadb.com/MultiLangProgGuide/pythonprogram.html#python-get) says.

  > If the underlying ydb_get_s() / ydb_get_st() call returns an error of GVUNDEF or LVUNDEF,
  > the function returns a value of None and does not raise an exception.

Issue
-----
* But the code did not implement the above. `get()` raised an exception even for the
  GVUNDEF/LVUNDEF case (line 1521 below).

  **_yottadb.c**
  ```c
   1508         /* Call the wrapped function */
   1509         status = ydb_get_s(&varname_ydb, subs_used, subsarray_ydb, &ret_value);
      .
      .
   1520         if (YDB_OK != status) {
   1521                 raise_YDBError(status);
  ```

* This was okay since the `raise_YDBError()` call would do a `ydb_zstatus()` call and that would
  get the `$zstatus` string containing the GVUNDEF/LVUNDEF error.

* But as part of YottaDB/DB/YDB@63f4847b3 (YottaDB/DB/YDB#1164), `ydb_get_s()` was changed to
  no longer populate `$zstatus` in the GVUNDEF/LVUNDEF case.

* And that meant line 1521 did not work correctly. It used a `stale` value of `$zstatus`. That is,
  whatever was the most recent error before the `ydb_get_s()` call is what would be propagated
  to the caller.

* Various tests in the YDBTest project that invoke `com/imptp.csh` failed with errors like the
  following as a result when they invoked the YDBPython wrapper randomly (`com/imptp.py`).

  ```
  ##HOST##:##TEST_PATH##/repl_misc_qual_1_23/repl_misc_qual/impjob_imptp0.mje1
  _yottadb.YDBError: 150375522,(SimpleAPI),%YDB-E-INVSTRLEN, Invalid string length 263: max 32
  ```

  In this case, the `INVSTRLEN` error was left over from a previous call and did not correspond
  to the `GVUNDEF` or `LVUNDEF` error that `imptp.py` was expecting to see.

Fix
---
* This commit fixes the YDBPython code to be in sync with the documentation as well as to work
  with YottaDB/DB/YDB@63f4847b3 by returning `Py_None` from the `get()` function in `_yottadb.c`
  in case of a `YDB_ERR_GVUNDEF` or `YDB_ERR_LVUNDEF` return from `ydb_get_s()`.