[#60] Fixed UnicodeDecodeError in string representation of Node/Key objects
Background
----------

Previously, code like:

```python
import yottadb

ckey = yottadb.Key("^ttest")[b'\x048}\xdc\xb4\xa2\x84\x878>\xe3tVm\xcd\xceD\xbc\x04\xe1\xd2\x1am\xc1!)/\x9a\x84\xf2']
print(f"{ckey}")
```

Would result in an a UnicodeDecodeError like:

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdc in position 9: ordinal not in range(128)
```

This is due to Python interpreting `\x` as the start of a hex byte, which is possible is ZWR strings within double quotes `"`. As in the above example, which may be converted to either of the following:

```python
b'$C(4)_"8}\xdc\xb4\xa2"_$C(132,135)_"8>\xe3tVm\xcd\xceD\xbc"_$C(4)_"\xe1\xd2"_$C(26)_"m\xc1!)/"_$C(154,132)_"\xf2"'  # M mode
b'$C(4)_"8}\xdc\xb4"_$ZCH(162,132,135)_"8>"_$ZCH(227)_"tVm"_$ZCH(205,206)_"D"_$ZCH(188)_$C(4)_$ZCH(225,210)_$C(26)_"m"_$ZCH(193)_"!)/"_$ZCH(154,132,242)'  # UTF-8 mode
```

Fix
---

The fix is to have the `Node.__str__()` method use `repr()` to convert subscript names instead of `str2zwr`, thus avoiding the encoding problems described above.

This change is tested by an addition to the `test_Node___repr__()` and `test_Node___str__()` test cases in `tests/test_yottadb.py` and an addition to the `str2zwr_tests` data set in `tests/conftests.py`.

Miscellaneous
-------------

Single- and double-quotes were changed in various places to conform to the code formatter, `black`, and pass the `code-format-check` pipeline job.